#!/bin/bash
WEB_PID="web.pidfile"
WEB_LOG="web.log"

if [ -f $WEB_PID ]; then
  echo "kill web server"
  kill `cat $WEB_PID`
  rm $WEB_PID
  sleep 0.2
fi

echo "start web server"
bundle exec rackup -s thin >$WEB_LOG 2>&1 &
echo $! >$WEB_PID

