#!/bin/sh
WEB_PID="web.pidfile"
WS_PID="ws.pidfile"

if [ -f $WEB_PID ]; then
  echo "kill web server"
  kill `cat $WEB_PID`
  rm $WEB_PID
  sleep 0.1
fi

if [ -f $WS_PID ]; then
  echo "kill websocket server"
  kill `cat $WS_PID`
  rm $WS_PID
  sleep 0.1
fi

echo "start web server"
bundle exec rackup >log.web.txt 2>&1 &
echo $! >$WEB_PID

sleep 0.1

echo "start websocket server"
bundle exec ruby ./websocket.rb >log.ws.txt 2>&1  &
echo $! >$WS_PID

